GEMINI_API_KEY="AIzaSyCH5reuwg4qSzrInax6kdIUKICU_2ALnik"
# Email Configuration
EMAIL_SENDER_ADDRESS = "abdullah75farid@gmail.com"
EMAIL_SENDER_PASSWORD = "rfwc xgtz qyum apql" 
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
